# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# NOTE! THIS FILE IS AUTOMATICALLY GENERATED AND WILL BE OVERWRITTEN!
#
# IF YOU WANT TO MODIFY THIS FILE, YOU SHOULD MODIFY THE TEMPLATE
# `get_provider_info_TEMPLATE.py.jinja2` IN the `dev/breeze/src/airflow_breeze/templates` DIRECTORY


def get_provider_info():
    return {
        "package-name": "apache-airflow-providers-arenadata-hbase",
        "name": "Arenadata HBase",
        "description": "`Apache HBase <https://hbase.apache.org/>`__ provider by Arenadata\n",
        "integrations": [
            {
                "integration-name": "HBase",
                "external-doc-url": "https://hbase.apache.org/",
                "how-to-guide": [
                    "/docs/apache-airflow-providers-arenadata-hbase/operators.rst",
                    "/docs/apache-airflow-providers-arenadata-hbase/connections.rst",
                ],
                "tags": ["apache", "database"],
            }
        ],
        "operators": [
            {
                "integration-name": "HBase",
                "python-modules": ["airflow.providers.arenadata.hbase.operators.hbase"],
            }
        ],
        "sensors": [
            {
                "integration-name": "HBase",
                "python-modules": ["airflow.providers.arenadata.hbase.sensors.hbase"],
            }
        ],
        "hooks": [
            {"integration-name": "HBase", "python-modules": ["airflow.providers.arenadata.hbase.hooks.hbase"]}
        ],
        "connection-types": [
            {
                "hook-class-name": "airflow.providers.arenadata.hbase.hooks.hbase.HBaseThriftHook",
                "connection-type": "hbase",
            },
            {
                "hook-class-name": "airflow.providers.arenadata.hbase.hooks.hbase_cli.HBaseCLIHook",
                "connection-type": "hbase",
            },
        ],
    }
