# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

# NOTE! THIS FILE IS AUTOMATICALLY GENERATED AND WILL BE OVERWRITTEN!
#
# IF YOU WANT TO MODIFY THIS FILE, YOU SHOULD MODIFY THE TEMPLATE
# `get_provider_info_TEMPLATE.py.jinja2` IN the `dev/breeze/src/airflow_breeze/templates` DIRECTORY


def get_provider_info():
    return {
        "package-name": "apache-airflow-providers-arenadata-ozone",
        "name": "Apache Ozone",
        "description": "`Apache Ozone <https://ozone.apache.org/>`__\n\nProvider package for interacting with Apache Ozone via:\n\n- Native CLI (``ozone``) for ``ofs://`` / ``o3fs://`` paths\n- Native Ozone administration and filesystem workflows\n",
        "integrations": [
            {
                "integration-name": "Apache Ozone",
                "external-doc-url": "https://ozone.apache.org/",
                "tags": ["apache"],
            }
        ],
        "hooks": [
            {
                "integration-name": "Apache Ozone",
                "python-modules": ["airflow.providers.arenadata.ozone.hooks.ozone"],
            }
        ],
        "operators": [
            {
                "integration-name": "Apache Ozone",
                "python-modules": ["airflow.providers.arenadata.ozone.operators.ozone"],
            }
        ],
        "sensors": [
            {
                "integration-name": "Apache Ozone",
                "python-modules": ["airflow.providers.arenadata.ozone.sensors.ozone"],
            }
        ],
        "transfers": [
            {
                "source-integration-name": "Hadoop Distributed File System (HDFS)",
                "target-integration-name": "Apache Ozone",
                "python-module": "airflow.providers.arenadata.ozone.transfers.hdfs_to_ozone",
            },
            {
                "source-integration-name": "Apache Ozone",
                "target-integration-name": "Apache Ozone",
                "python-module": "airflow.providers.arenadata.ozone.transfers.ozone_backup",
            },
        ],
        "connection-types": [
            {
                "hook-class-name": "airflow.providers.arenadata.ozone.hooks.ozone.OzoneCliHook",
                "connection-type": "ozone",
            }
        ],
    }
